name: run_blog_fe

on: 
  push:
    branches: [main]
    
jobs:
  run-blog-fe:
    runs-on: 
      - ubuntu-latest
      - self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run dev
      - run: mkdir actions-runner && cd actions-runner
      - run: curl -o actions-runner-linux-x64-2.309.0.tar.gz -L https://github.com/actions/runner/releases/download/v2.309.0/actions-runner-linux-x64-2.309.0.tar.gz
      - run: echo "2974243bab2a282349ac833475d241d5273605d3628f0685bd07fb5530f9bb1a  actions-runner-linux-x64-2.309.0.tar.gz" | shasum -a 256 -c
      - run: tar xzf ./actions-runner-linux-x64-2.309.0.tar.gz
      - run: ./config.sh --url https://github.com/lebaohuan1998/Blog --token AR3PVEW4PCDYM3LEPAGZFO3FDB2W6
      - run: ./run.sh
  
