name: run_blog_fe

on: 
  push:
    branches: [main]
    
jobs:
  run-blog-fe:
    runs-on: 
      - self-hosted

    strategy:
      matrix:
        node-version: [14.x]
      
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - run: npm run dev --if--present
  
